version: '3'
services:
    app:
        build: .
        ports:
            - "3000:3000"
        links:
            - database
        environment:
            - MONGO_URL=mongodb://database:27017/testing
            - ROOT_URL=http://18.221.137.142
            - PORT=3000
    database:
        image: mongo:3.4.1
        restart: always
        volumes:
            - "/home/ec2-user/stag_data:/data/db"
